# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Leee Jeffries Blog"
strapline: "LEEEJEFFRIES.COM"
email: leee.jeffries@leeejeffries.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog all about my experiences in EUC using all types of technologies, tips and tricks.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.leeejeffries.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: leeej84/leeejeffries.github.io
twitter: leeejeffries
github: leeej84
linkedin: leee-jeffries-0021752a

header_image: assets/profile.png

google_analytics: UA-97815584-1
comments: true
disqus: purelog-jekyll

author: Leee Jeffries
author_bio: >-
  I'm an IT professional with over 15 years of experience in the IT industry, I've worked in many fields in my career. This blog is to share my experience, tips and tricks.
author_pic: assets/profile-sm.png
paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Leee Jeffries
      avatar: assets/profile-sm.png

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
